const SET_AMOUNT = "SET_AMOUNT";
const SET_RATES = "SET_RATES";
const REMOVE_CURRENCY = "REMOVE_CURRENCY";
const ADD_CURRENCY = "ADD_CURRENCY";

export default {
  SET_AMOUNT,
  SET_RATES,
  REMOVE_CURRENCY,
  ADD_CURRENCY
}